add_newline = false

format = "$directory$git_branch$git_status$cmd_duration$line_break$character"

[directory]
truncation_length = 4
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = "î‚  "
style = "bold purple"

[git_status]
style = "bold yellow"

[cmd_duration]
min_time = 300
format = "took [$duration]($style) "
style = "bold green"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold blue)"
