add_newline = false

format = "$username[@](fg:244)$hostname [in](fg:244) $directory$git_branch$git_status$line_break$character"
right_format = "$cmd_duration"

[username]
show_always = true
style_user = "bold fg:111"
style_root = "bold fg:203"
format = "[$user ]($style)"

[hostname]
ssh_only = false
style = "bold fg:214"
format = "[$hostname]($style)"

[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = ".../"
read_only = " ro"
style = "bold fg:39"
format = "[$path]($style)[$read_only](bold fg:203) "

[git_branch]
style = "bold fg:141"
format = " [on](fg:244) [$branch]($style)"

[git_status]
style = "bold fg:178"
format = "[($all_status$ahead_behind)]($style)"


[cmd_duration]
min_time = 300
style = "bold fg:70"
format = "[$duration]($style) "

[status]
disabled = false
style = "bold fg:203"
format = "[$symbol$status]($style) "
symbol = "x"

[jobs]
symbol = "jobs:"
style = "bold fg:110"
format = "[$symbol$number]($style) "

[time]
disabled = false
time_format = "%H:%M"
style = "bold fg:244"
format = "[$time]($style)"

[character]
success_symbol = "[>](bold fg:76)"
error_symbol = "[>](bold fg:203)"
vimcmd_symbol = "[<](bold fg:39)"
vimcmd_replace_one_symbol = "[<](bold fg:214)"
vimcmd_replace_symbol = "[<](bold fg:214)"
vimcmd_visual_symbol = "[<](bold fg:178)"
